#!/sbin/openrc-run

configfile="${FLUENT_BIT_CONF:-/etc/fluent-bit/fluent-bit.conf}"
logfile="/var/log/fluent-bit/fluent-bit.log"

command=/usr/bin/fluent-bit
command_args="--config=${configfile} --log_file=${logfile} ${FLUENT_BIT_OPTS}"
command_background=yes
command_user=fluent-bit:logger
directory=`dirname "${configfile}"`
pidfile=/var/run/fluent-bit.pid
make_pidfile=yes
retry="${FLUENT_BIT_STOP_TIMEOUT:-60}"
