#!/sbin/openrc-run
# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Mattermost collaboration server"
pidfile=${pidfile:-"/run/${RC_SVCNAME}.pid"}
command="/opt/mattermost/bin/mattermost"
command_user="${command_user:-"mattermost:mattermost"}"
command_args="${command_args:-"--config /etc/mattermost/config.json"}"
command_background="true"
logfile="${logfile:-"/var/log/mattermost/${RC_SVCNAME}.log"}"
start_stop_daemon_args="--chdir /opt/mattermost --user ${command_user%:*} --group ${command_user#*:} --stdout ${logfile} --stderr ${logfile}"

: "${supervisor:=supervise-daemon}"
: "${respawn_delay:=5}"
: "${respawn_max:=10}"
: "${respawn_period:=60}"

depend() {
	need net
	use postgresql
}
